### ISSUE TITLE
Report view not selectable on Windows 10

### ISSUE THREAD

**Issue by company-jcup** [Daimler/sechub-plugin-eclipse#7]
When importing a test report file the report view table is filled, but I am not able to select entries:

![image](https://user-images.githubusercontent.com/80676663/113166179-cf660a80-9242-11eb-9881-a80eaa011273.png)

Tested environments:
- Windows 10

Tested Eclipse Versions
- Eclipse Java IDE 2021-3
- Eclipse Java IDE 2020-12

Tested plugin version
- SecHub eclipse plugin 0.2.0

No specific log etnries/data found inside ErrorLog view.

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by company-jcup** [comment]
With Eclipse Java IDE 2020-12 + Linux (Debian based) + same plugin version does work "out-of-the-box"

**Comment by de-jcup** [comment]
After a long search ... I found the problem.  At Windows SWT it is necessary to create the Tree viewer with SWT flag `SWT.FULL_SELECTION`... otherwise only the first column is selectable. At Linux SWT this is not necessary... :facepalm:
